name: quran_com
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  sizer: ^3.0.4
  flutter_svg: ^2.0.10+1
  rxdart: ^0.28.0
  flutter_modular: ^6.3.4
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  get_it: ^8.0.2
  provider: ^6.1.2
  speech_to_text: ^7.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
